import "../index.css";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import { Metadata } from "next";
import { FacultyProvider } from "../contexts/FacultyContext";
import { getFacultyData } from "../hooks/useFetchDataFaculty";
import { DocumentProvider } from "../contexts/DocumentContext";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const faculty = await getFacultyData();
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col">
          <Navbar />
          <div className="pt-20">
            <DocumentProvider>
              <FacultyProvider faculty={faculty}>{children}</FacultyProvider>
            </DocumentProvider>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}

